name: Pull request
on:
  pull_request:
    types: [ opened, reopened, synchronize ]
jobs:
  pr-check:
    name: PR check for graph-serializer
    runs-on: ubuntu-latest
    if: github.repository == 'ScientaNL/graph-serializer'
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: yarn
      - run: yarn test

