name: Pull request
on:
  pull_request:
    types: [ opened, reopened, synchronize ]
jobs:
  pr-check:
    name: PR check for graph-serializer
    runs-on: ubuntu-latest
    if: github.repository == 'ScientaNL/graph-serializer'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '12.x'
      - run: yarn
      - run: yarn test

